version: '3'
services:
  server:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/app # Mount the frontend directory to the container
    ports:
      - "3000:3000"
